-- データベース初期化スクリプト
-- 全テーブルとEnumを削除

-- 外部キー制約があるため、依存関係の逆順で削除
DROP TABLE IF EXISTS room_member CASCADE;
DROP TABLE IF EXISTS player_session CASCADE;
DROP TABLE IF EXISTS vote CASCADE;
DROP TABLE IF EXISTS answer CASCADE;
DROP TABLE IF EXISTS round CASCADE;
DROP TABLE IF EXISTS question CASCADE;
DROP TABLE IF EXISTS game_session CASCADE;
DROP TABLE IF EXISTS room CASCADE;
DROP TABLE IF EXISTS verificationToken CASCADE;
DROP TABLE IF EXISTS session CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS user CASCADE;

-- Enumタイプを削除
DROP TYPE IF EXISTS room_status CASCADE;
DROP TYPE IF EXISTS session_status CASCADE;
DROP TYPE IF EXISTS round_status CASCADE;
DROP TYPE IF EXISTS player_status CASCADE;
DROP TYPE IF EXISTS difficulty CASCADE;